### ISSUE TITLE
Segmentation fault on addNewWords

### ISSUE THREAD

**Issue by CelestialBoon** [introlab/rtabmap#241]
rtabmap (standalone) has begun crashing on me after I've compiled and ran the RGB-D Mapping c++ example in the examples section (using a Kinect 360). When the sample program is ran, it exits immediately after the first frame shows, citing a segmentation fault. From there onwards, rtabmap also crashes, when mapping (also crashes right after starting to map, as soon as 2 frames get registered and mapped out on screen) and also when postprocessing (just after pressing Ok on the menu). Below are the details of the installation, and the conditions surrounding a postprocessing crash (they are very similar to the mapping one from what I've seen).

The Cmake output:
```
-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-6.2/VTKTargets.cmake"
but not all the files it references.

-- Could NOT find PCL_APPS (missing:  PCL_APPS_LIBRARY) 
-- Found OpenMP
-- Found OpenCV: /opt/ros/kinetic/include/opencv-3.2.0-dev;/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv
-- Found PCL: /usr/include/pcl-1.7;/usr/include/eigen3;/usr/include;/usr/include/ni;/usr/include/openni2;/usr/include/vtk-6.2;/usr/include/freetype2;/usr/include/x86_64-linux-gnu/freetype2;/usr/include/x86_64-linux-gnu;/usr/include/python2.7;/usr/include/jsoncpp;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi;/usr/include/hdf5/openmpi;/usr/include/libxml2;/usr/include/tcl
-- Found ZLIB: /usr/include
-- Found Freenect: /usr/include
-- Found freenect2: /usr/local/include
-- Found OpenNI2: /usr/include/openni2
-- Found g2o: /opt/ros/kinetic/include;/usr/include/suitesparse;/usr/include/suitesparse
-- GTSAM include directory:  /usr/local/lib/cmake/GTSAM/../../../include;/usr/include;/usr/local/include/gtsam/3rdparty/Eigen/
-- Found octomap: /opt/ros/kinetic/include
-- Found Pthreads
-- --------------------------------------------
-- Info :
--   Version : 0.14.2
--   CMAKE_INSTALL_PREFIX = /usr/local
--   CMAKE_BUILD_TYPE =     Release
--   CMAKE_INSTALL_LIBDIR = lib
--   BUILD_APP =            ON
--   BUILD_TOOLS =          ON
--   BUILD_EXAMPLES =       ON
--   BUILD_SHARED_LIBS =    ON
--   CMAKE_CXX_FLAGS =  -fmessage-length=0  -fopenmp -std=c++11
--   With OpenCV 3 xfeatures2d module (SIFT/SURF/BRIEF/FREAK) = YES (License: Non commercial)
--   With Freenect             = YES (License: Apache v2 and/or GPLv2)
--   With OpenNI2              = YES (License: Apache v2)
--   With Freenect2            = YES (License: Apache v2 and/or GPLv2)
--   With dc1394               = NO (dc1394 not found)
--   With FlyCapture2/Triclops = NO (Point Grey SDK not found)
--   With TORO                 = YES (License: Creative Commons [Attribution-NonCommercial-ShareAlike])
--   With g2o                  = YES (License: BSD)
--   With GTSAM                = YES (License: BSD)
--   With VERTIGO              = YES (License: GPLv3)
--   With cvsba                = NO (cvsba not found)
--   With libpointmatcher      = NO (libpointmatcher not found)
--   With ZED                  = NO (ZED sdk not found)
--   With RealSense            = NO (librealsense not found)
--   With OCTOMAP              = YES (License: BSD)
--   With CPUTSDF              = NO (CPUTSDF not found)
--   With libfovis             = NO (libfovis not found)
--   With libviso2             = NO (libviso2 not found)
--   With dvo_core             = NO (dvo_core not found)
--   With ORB_SLAM2            = NO (WITH_G2O should be OFF as ORB_SLAM2 uses its own g2o version)
--   With Qt5                  = YES (License: Open Source or Commercial)
-- --------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/celestial/ext/rtabmap/build
```

The gdb backtrace:
```
#0  0x00007ffff4ad5428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4ad702a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff4b177ea in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff4b2037a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff4b2453c in free () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff6148321 in cv::MatAllocator::unmap(cv::UMatData*) const ()
   from /opt/ros/kinetic/lib/libopencv_core3.so.3.2
#6  0x00007ffff6148f1c in cv::Mat::deallocate() () from /opt/ros/kinetic/lib/libopencv_core3.so.3.2
#7  0x00007ffff70ac44d in rtabmap::VWDictionary::addNewWords[abi:cxx11](cv::Mat const&, int) ()
   from /usr/local/lib/librtabmap_core.so.0.14
#8  0x00007ffff728156a in rtabmap::RegistrationVis::computeTransformationImpl(rtabmap::Signature&, rtabmap::Signature&, rtabmap::Transform, rtabmap::RegistrationInfo&) const ()
   from /usr/local/lib/librtabmap_core.so.0.14
#9  0x00007ffff7267321 in rtabmap::Registration::computeTransformationMod(rtabmap::Signature&, rtabmap::Signature&, rtabmap::Transform, rtabmap::RegistrationInfo*) const ()
   from /usr/local/lib/librtabmap_core.so.0.14
#10 0x00007ffff72c6094 in rtabmap::OdometryF2M::computeTransform(rtabmap::SensorData&, rtabmap::Transform const&, rtabmap::OdometryInfo*) () from /usr/local/lib/librtabmap_core.so.0.14
#11 0x00007ffff72b3bd8 in rtabmap::Odometry::process(rtabmap::SensorData&, rtabmap::Transform const&, rtabmap::OdometryInfo*) () from /usr/local/lib/librtabmap_core.so.0.14
#12 0x00007ffff72b7387 in rtabmap::Odometry::process(rtabmap::SensorData&, rtabmap::OdometryInfo*)
    () from /usr/local/lib/librtabmap_core.so.0.14
#13 0x00007ffff72c56f4 in rtabmap::OdometryThread::mainLoop() ()
   from /usr/local/lib/librtabmap_core.so.0.14
#14 0x00007ffff6c4b5b9 in UThreadC<void>::ThreadMainHandler(UThreadC<void>::Instance*) ()
   from /usr/local/lib/librtabmap_utilite.so.0.14
#15 0x00007ffff46866ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#16 0x00007ffff4ba73dd in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

The debug output (last part):
```
[DEBUG] (2017-10-19 15:17:31.934) util2d.cpp:1146::computeRoi() roi ratios = 0,000000, 0,000000, 0,000000, 0,000000
[DEBUG] (2017-10-19 15:17:31.934) util2d.cpp:1147::computeRoi() roi = 0, 0, 640, 480
[DEBUG] (2017-10-19 15:17:31.934) util2d.cpp:1174::computeRoi() roi = 0, 0, 640, 480
[DEBUG] (2017-10-19 15:17:31.942) Features2d.cpp:540::generateKeypoints() Keypoints extraction time = 0,008003 s, keypoints extracted = 4 (mask empty=0)
[DEBUG] (2017-10-19 15:17:31.942) RegistrationVis.cpp:510::computeTransformationImpl() kptsFrom=24
[DEBUG] (2017-10-19 15:17:31.942) RegistrationVis.cpp:511::computeTransformationImpl() kptsTo=4
[DEBUG] (2017-10-19 15:17:31.942) Features2d.cpp:584::generateDescriptors() Descriptors extracted = 4, remaining kpts=4
[DEBUG] (2017-10-19 15:17:31.942) RegistrationVis.cpp:710::computeTransformationImpl() descriptorsFrom=24
[DEBUG] (2017-10-19 15:17:31.942) RegistrationVis.cpp:711::computeTransformationImpl() descriptorsTo=4
[DEBUG] (2017-10-19 15:17:31.942) RegistrationVis.cpp:960::computeTransformationImpl() 
[DEBUG] (2017-10-19 15:17:31.942) VWDictionary.cpp:307::update() 
[DEBUG] (2017-10-19 15:17:31.942) VWDictionary.cpp:507::update() Dictionary updated! (size=0 added=0 removed=0)
[DEBUG] (2017-10-19 15:17:31.942) VWDictionary.cpp:515::update() 
[DEBUG] (2017-10-19 15:17:31.942) VWDictionary.cpp:307::update() 
[DEBUG] (2017-10-19 15:17:31.942) VWDictionary.cpp:322::update() Incremental FLANN: Removing 0 words...
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:331::update() Incremental FLANN: Removing 0 words... done!
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:335::update() Incremental FLANN: Inserting 24 words...
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:362::update() Building FLANN index...
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:380::update() Building FLANN index... done!
[DEBUG] (2017-10-19 15:17:31.943) FlannIndex.cpp:338::addPoints() Rebuilding FLANN index: 1 -> 3
[DEBUG] (2017-10-19 15:17:31.943) FlannIndex.cpp:338::addPoints() Rebuilding FLANN index: 3 -> 7
[DEBUG] (2017-10-19 15:17:31.943) FlannIndex.cpp:338::addPoints() Rebuilding FLANN index: 7 -> 15
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:394::update() Incremental FLANN: Inserting 24 words... done!
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:507::update() Dictionary updated! (size=0 added=24 removed=0)
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:515::update() 
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:593::addNewWords() id=2 descriptors=4
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:686::addNewWords() newPts.total()=4 
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:751::addNewWords() Time to find nn = 0,000046 s
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:872::addNewWords() naive search and add ref/words time = 0,000018 s
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:874::addNewWords() 4 new words added...
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:876::addNewWords() 0 duplicated words added (from current image = 0)...
[DEBUG] (2017-10-19 15:17:31.943) VWDictionary.cpp:877::addNewWords() total time 0,000088s
*** Error in `/usr/local/bin/rtabmap': free(): invalid next size (fast): 0x00007fff68011630 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffff4b177e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ffff4b2037a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ffff4b2453c]
/opt/ros/kinetic/lib/libopencv_core3.so.3.2(_ZNK2cv12MatAllocator5unmapEPNS_8UMatDataE+0x91)[0x7ffff6148321]
/opt/ros/kinetic/lib/libopencv_core3.so.3.2(_ZN2cv3Mat10deallocateEv+0x1c)[0x7ffff6148f1c]
/usr/local/lib/librtabmap_core.so.0.14(_ZN7rtabmap12VWDictionary11addNewWordsB5cxx11ERKN2cv3MatEi+0x158d)[0x7ffff70ac44d]
/usr/local/lib/librtabmap_core.so.0.14(_ZNK7rtabmap15RegistrationVis25computeTransformationImplERNS_9SignatureES2_NS_9TransformERNS_16RegistrationInfoE+0x636a)[0x7ffff728156a]
/usr/local/lib/librtabmap_core.so.0.14(_ZNK7rtabmap12Registration24computeTransformationModERNS_9SignatureES2_NS_9TransformEPNS_16RegistrationInfoE+0x3d1)[0x7ffff7267321]
/usr/local/lib/librtabmap_core.so.0.14(_ZN7rtabmap11OdometryF2M16computeTransformERNS_10SensorDataERKNS_9TransformEPNS_12OdometryInfoE+0x304)[0x7ffff72c6094]
/usr/local/lib/librtabmap_core.so.0.14(_ZN7rtabmap8Odometry7processERNS_10SensorDataERKNS_9TransformEPNS_12OdometryInfoE+0x1d38)[0x7ffff72b3bd8]
/usr/local/lib/librtabmap_core.so.0.14(_ZN7rtabmap8Odometry7processERNS_10SensorDataEPNS_12OdometryInfoE+0x47)[0x7ffff72b7387]
/usr/local/lib/librtabmap_core.so.0.14(_ZN7rtabmap14OdometryThread8mainLoopEv+0x414)[0x7ffff72c56f4]
/usr/local/lib/librtabmap_utilite.so.0.14(_ZN8UThreadCIvE17ThreadMainHandlerEPNS0_8InstanceE+0xf9)[0x7ffff6c4b5b9]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7ffff46866ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7ffff4ba73dd]
======= Memory map: ========
00400000-0040b000 r-xp 00000000 08:01 16388441                           /usr/local/bin/rtabmap
0060a000-0060b000 r--p 0000a000 08:01 16388441                           /usr/local/bin/rtabmap
0060b000-0060c000 rw-p 0000b000 08:01 16388441                           /usr/local/bin/rtabmap
0060c000-0518a000 rw-p 00000000 00:00 0                                  [heap]
7fff50000000-7fff50021000 rw-p 00000000 00:00 0 
7fff50021000-7fff54000000 ---p 00000000 00:00 0 
7fff58000000-7fff58021000 rw-p 00000000 00:00 0 
7fff58021000-7fff5c000000 ---p 00000000 00:00 0 
7fff5f7ff000-7fff5f800000 ---p 00000000 00:00 0 
7fff5f800000-7fff60000000 rwxp 00000000 00:00 0 
7fff60000000-7fff60053000 rw-p 00000000 00:00 0 
7fff60053000-7fff64000000 ---p 00000000 00:00 0 
7fff64000000-7fff6414c000 rw-p 00000000 00:00 0 
7fff6414c000-7fff68000000 ---p 00000000 00:00 0 
7fff68000000-7fff6888f000 rw-p 00000000 00:00 0 
7fff6888f000-7fff6c000000 ---p 00000000 00:00 0 
7fff6c000000-7fff6c021000 rw-p 00000000 00:00 0 
7fff6c021000-7fff70000000 ---p 00000000 00:00 0 
7fff70000000-7fff70021000 rw-p 00000000 00:00 0 
7fff70021000-7fff74000000 ---p 00000000 00:00 0 
7fff74000000-7fff74021000 rw-p 00000000 00:00 0 
7fff74021000-7fff78000000 ---p 00000000 00:00 0 
7fff78000000-7fff78021000 rw-p 00000000 00:00 0 
7fff78021000-7fff7c000000 ---p 00000000 00:00 0 
7fff7c7f9000-7fff7c7fa000 ---p 00000000 00:00 0 
7fff7c7fa000-7fff7cffa000 rwxp 00000000 00:00 0 
7fff7cffa000-7fff7cffb000 ---p 00000000 00:00 0 
7fff7cffb000-7fff7d7fb000 rwxp 00000000 00:00 0 
7fff7d7fb000-7fff7d7fc000 ---p 00000000 00:00 0 
7fff7d7fc000-7fff7dffc000 rwxp 00000000 00:00 0 
7fff7dffc000-7fff7dffd000 ---p 00000000 00:00 0 
7fff7dffd000-7fff7e7fd000 rwxp 00000000 00:00 0 
7fff7e7fd000-7fff7e7fe000 ---p 00000000 00:00 0 
7fff7e7fe000-7fff7effe000 rwxp 00000000 00:00 0 
7fff7effe000-7fff7efff000 ---p 00000000 00:00 0 
7fff7efff000-7fff7f7ff000 rwxp 00000000 00:00 0 
7fff7f7ff000-7fff7f800000 ---p 00000000 00:00 0 
7fff7f800000-7fff80000000 rwxp 00000000 00:00 0 
7fff80000000-7fff80021000 rw-p 00000000 00:00 0 
7fff80021000-7fff84000000 ---p 00000000 00:00 0 
7fff84000000-7fff84021000 rw-p 00000000 00:00 0 
7fff84021000-7fff88000000 ---p 00000000 00:00 0 
7fff88000000-7fff88021000 rw-p 00000000 00:00 0 
7fff88021000-7fff8c000000 ---p 00000000 00:00 0 
7fff8c000000-7fff8c021000 rw-p 00000000 00:00 0 
7fff8c021000-7fff90000000 ---p 00000000 00:00 0 
7fff90000000-7fff906af000 rw-p 00000000 00:00 0 
7fff906af000-7fff94000000 ---p 00000000 00:00 0 
7fff94000000-7fff94021000 rw-p 00000000 00:00 0 
7fff94021000-7fff98000000 ---p 00000000 00:00 0 
7fff98000000-7fff98021000 rw-p 00000000 00:00 0 
7fff98021000-7fff9c000000 ---p 00000000 00:00 0 
7fff9c14e000-7fff9c14f000 ---p 00000000 00:00 0 
7fff9c14f000-7fff9c94f000 rwxp 00000000 00:00 0 
7fff9c94f000-7fff9c950000 ---p 00000000 00:00 0 
7fff9c950000-7fff9d150000 rwxp 00000000 00:00 0 
7fff9d150000-7fff9d151000 ---p 00000000 00:00 0 
7fff9d151000-7fff9d951000 rwxp 00000000 00:00 0 
7fff9d951000-7fff9d952000 ---p 00000000 00:00 0 
7fff9d952000-7fff9e152000 rwxp 00000000 00:00 0 
7fff9e152000-7fff9e153000 ---p 00000000 00:00 0 
7fff9e153000-7fff9e953000 rwxp 00000000 00:00 0 
7fff9e953000-7fff9ebac000 rw-p 00000000 00:00 0 
7fff9ebac000-7fff9ebad000 ---p 00000000 00:00 0 
7fff9ebad000-7fff9f3ad000 rwxp 00000000 00:00 0 
7fff9f3ad000-7fff9f3ae000 ---p 00000000 00:00 0 
7fff9f3ae000-7fff9fbae000 rwxp 00000000 00:00 0 
7fff9fbae000-7fff9fc9a000 rw-s 00000000 00:05 21332046                   /SYSV00000000 (deleted)
7fff9fc9a000-7fff9ff44000 rw-s 00000000 00:05 21135435                   /SYSV00000000 (deleted)
7fff9ff44000-7fff9ff56000 r-xp 00000000 08:01 16387376                   /usr/lib/x86_64-linux-gnu/beignet/libgbeinterp.so
7fff9ff56000-7fffa0156000 ---p 00012000 08:01 16387376                   /usr/lib/x86_64-linux-gnu/beignet/libgbeinterp.so
7fffa0156000-7fffa0157000 r--p 00012000 08:01 16387376                   /usr/lib/x86_64-linux-gnu/beignet/libgbeinterp.so
7fffa0157000-7fffa0158000 rw-p 00013000 08:01 16387376                   /usr/lib/x86_64-linux-gnu/beignet/libgbeinterp.so
7fffa0158000-7fffa04d6000 rw-s 00000000 00:05 21233672                   /SYSV00000000 (deleted)
7fffa04d6000-7fffa04e9000 r-xp 00000000 08:01 44569007                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7fffa04e9000-7fffa06e8000 ---p 00013000 08:01 44569007                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7fffa06e8000-7fffa06e9000 r--p 00012000 08:01 44569007                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7fffa06e9000-7fffa06ea000 rw-p 00013000 08:01 44569007                   /lib/x86_64-linux-gnu/libbsd.so.0.8.2
7fffa06ea000-7fffa06eb000 rw-p 00000000 00:00 0 
7fffa06eb000-7fffa0710000 r-xp 00000000 08:01 44569179                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fffa0710000-7fffa090f000 ---p 00025000 08:01 44569179                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fffa090f000-7fffa0913000 r--p 00024000 08:01 44569179                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fffa0913000-7fffa0914000 rw-p 00028000 08:01 44569179                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7fffa0914000-7fffa0945000 r-xp 00000000 08:01 15998616                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7fffa0945000-7fffa0b45000 ---p 00031000 08:01 15998616                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7fffa0b45000-7fffa0b47000 r--p 00031000 08:01 15998616                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7fffa0b47000-7fffa0b48000 rw-p 00033000 08:01 15998616                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.53
7fffa0b48000-7fffa0b4c000 rw-p 00000000 00:00 0 
7fffa0b4c000-7fffa283d000 r-xp 00000000 08:01 15999265                   /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
7fffa283d000-7fffa283e000 ---p 01cf1000 08:01 15999265                   /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
7fffa283e000-7fffa2a53000 r--p 01cf1000 08:01 15999265                   /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
7fffa2a53000-7fffa2a59000 rw-p 01f06000 08:01 15999265                   /usr/lib/x86_64-linux-gnu/libLLVM-3.6.so.1
7fffa2a59000-7fffa2a6e000 rw-p 00000000 00:00 0 
7fffa2a6e000-7fffa3b0d000 r-xp 00000000 08:01 16385351                   /usr/lib/x86_64-linux-gnu/beignet/libgbe.so
7fffa3b0d000-7fffa3d0c000 ---p 0109f000 08:01 16385351                   /usr/lib/x86_64-linux-gnu/beignet/libgbe.so
7fffa3d0c000-7fffa3d98000 r--p 0109e000 08:01 16385351                   /usr/lib/x86_64-linux-gnu/beignet/libgbe.so
7fffa3d98000-7fffa3da0000 rw-p 0112a000 08:01 16385351                   /usr/lib/x86_64-linux-gnu/beignet/libgbe.so
7fffa3da0000-7fffa3da2000 rw-p 00000000 00:00 0 
7fffa3da2000-7fffa3dde000 r-xp 00000000 08:01 16387375                   /usr/lib/x86_64-linux-gnu/beignet/libcl.so
7fffa3dde000-7fffa3fde000 ---p 0003c000 08:01 16387375                   /usr/lib/x86_64-linux-gnu/beignet/libcl.so
7fffa3fde000-7fffa3fdf000 r--p 0003c000 08:01 16387375                   /usr/lib/x86_64-linux-gnu/beignet/libcl.so
7fffa3fdf000-7fffa3fff000 rw-p 0003d000 08:01 16387375                   /usr/lib/x86_64-linux-gnu/beignet/libcl.so
7fffa3fff000-7fffa4000000 rw-p 00000000 00:00 0 
7fffa4000000-7fffa50bf000 rw-p 00000000 00:00 0 
7fffa50bf000-7fffa8000000 ---p 00000000 00:00 0 
7fffa8000000-7fffa8022000 rw-p 00000000 00:00 0 
7fffa8022000-7fffac000000 ---p 00000000 00:00 0 
7fffac032000-7fffac03b000 rw-s 00000000 00:05 21168204                   /SYSV00000000 (deleted)
7fffac03b000-7fffac05f000 rw-s 00000000 00:05 21102666                   /SYSV00000000 (deleted)
7fffac05f000-7fffac0af000 rw-s 00000000 00:05 21069897                   /SYSV00000000 (deleted)
7fffac0af000-7fffac0b5000 rw-s 00000000 00:05 21037128                   /SYSV00000000 (deleted)
7fffac0b5000-7fffac0d6000 rw-s 00000000 00:05 21004359                   /SYSV00000000 (deleted)
7fffac0d6000-7fffac0fa000 rw-s 00000000 00:05 20938820                   /SYSV00000000 (deleted)
7fffac0fa000-7fffac17a000 rw-s 00000000 00:05 20906051                   /SYSV00000000 (deleted)
7fffac17a000-7fffac1f9000 rw-s 00000000 00:05 20873282                   /SYSV00000000 (deleted)
7fffac1f9000-7fffac1fa000 ---p 00000000 00:00 0 
7fffac1fa000-7fffac9fa000 rwxp 00000000 00:00 0 
7fffac9fa000-7fffacafa000 rw-s 10478b000 00:06 1404                      /dev/dri/card0
7fffacafa000-7fffaf1c4000 rw-p 00000000 00:00 0 
7fffaf1c4000-7fffaf1fb000 r-xp 00000000 08:01 15999482                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7fffaf1fb000-7fffaf3fa000 ---p 00037000 08:01 15999482                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7fffaf3fa000-7fffaf3fb000 r--p 00036000 08:01 15999482                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7fffaf3fb000-7fffaf3fc000 rw-p 00037000 08:01 15999482                   /usr/lib/x86_64-linux-gnu/libtxc_dxtn_s2tc.so.0.0.0
7fffaf401000-7fffaf43d000 rw-s 00000000 00:05 20840511                   /SYSV00000000 (deleted)
7fffaf43d000-7fffaf449000 r-xp 00000000 08:01 16123872                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7fffaf449000-7fffaf648000 ---p 0000c000 08:01 16123872                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7fffaf648000-7fffaf649000 r--p 0000b000 08:01 16123872                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7fffaf649000-7fffaf64a000 rw-p 0000c000 08:01 16123872                   /usr/lib/python2.7/lib-dynload/_json.x86_64-linux-gnu.so
7fffaf64a000-7fffaf68a000 rw-p 00000000 00:00 0 
7fffaf68a000-7fffaf6e8000 r-xp 00000000 08:01 44569173                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fffaf6e8000-7fffaf8e8000 ---p 0005e000 08:01 44569173                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fffaf8e8000-7fffaf8ec000 r--p 0005e000 08:01 44569173                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fffaf8ec000-7fffaf8f3000 rw-p 00062000 08:01 44569173                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fffaf8f4000-7fffaf934000 rw-p 00000000 00:00 0 
7fffaf934000-7fffaf949000 r-xp 00000000 08:01 16123877                   /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
7fffaf949000-7fffafb48000 ---p 00015000 08:01 16123877                   /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
7fffafb48000-7fffafb49000 r--p 00014000 08:01 16123877                   /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
7fffafb49000-7fffafb4d000 rw-p 00015000 08:01 16123877                   /usr/lib/python2.7/lib-dynload/_ssl.x86_64-linux-gnu.so
7fffafb4d000-7fffafd4d000 rw-p 00000000 00:00 0 
7fffafd4d000-7fffafdc3000 r-xp 00000000 08:01 20847645                   /usr/lib/python2.7/dist-packages/numpy/random/mtrand.x86_64-linux-gnu.so
7fffafdc3000-7fffaffc3000 ---p 00076000 08:01 20847645                   /usr/lib/python2.7/dist-packages/numpy/random/mtrand.x86_64-linux-gnu.so
7fffaffc3000-7fffaffc4000 r--p 00076000 08:01 20847645                   /usr/lib/python2.7/dist-packages/numpy/random/mtrand.x86_64-linux-gnu.so
7fffaffc4000-7fffaffff000 rw-p 00077000 08:01 20847645                   /usr/lib/python2.7/dist-packages/numpy/random/mtrand.x86_64-linux-gnu.so
7fffaffff000-7fffb0000000 rw-p 00000000 00:00 0 
7fffb0000000-7fffb0021000 rw-p 00000000 00:00 0 
7fffb0021000-7fffb4000000 ---p 00000000 00:00 0 
7fffb4004000-7fffb4013000 rw-s 00000000 00:05 20971590                   /SYSV00000000 (deleted)
7fffb4013000-7fffb401b000 rw-s 00000000 00:05 718310                     /drm mm object (deleted)
7fffb401b000-7fffb4023000 rw-s 00000000 00:05 718302                     /drm mm object (deleted)
7fffb4023000-7fffb402b000 rw-s 00000000 00:05 718297                     /drm mm object (deleted)
7fffb402b000-7fffb406b000 rw-p 00000000 00:00 0 
7fffb406b000-7fffb4074000 r-xp 00000000 08:01 20847825                   /usr/lib/python2.7/dist-packages/numpy/fft/fftpack_lite.x86_64-linux-gnu.so
Thread 17 "rtabmap" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff7e7fc700 (LWP 26642)]
0x00007ffff4ad5428 in raise () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by matlabbe** [comment]
Is it with the latest code from source? It seems related to that fix https://github.com/introlab/rtabmap/commit/4de2ed767b8e920b39ccbb9bdb35b9ec6b40f088.

cheers

**Comment by CelestialBoon** [comment]
It works! Thanks a bunch.
