### ISSUE TITLE
Error start Rtabmap in ROS2 Foxy branch

### ISSUE THREAD

**Issue by FPSychotic** [introlab/rtabmap#848]
```
ros2 launch rtabmap_ros rtabmap.launch.py
[INFO] [launch]: All log files can be found below /home/igcs/.ros/log/2022-04-12-22-11-15-711944-igcs-15786
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py:226> exception=TypeError("Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)")>
Traceback (most recent call last):
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  [Previous line repeated 2 more times]
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 444, in execute
    self._perform_substitutions(context)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/actions/node.py", line 399, in _perform_substitutions
    evaluated_parameters = evaluate_parameters(context, self.__parameters)
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 160, in evaluate_parameters
    output_params.append(evaluate_parameter_dict(context, param))
  File "/opt/ros/foxy/lib/python3.8/site-packages/launch_ros/utilities/evaluate_parameters.py", line 95, in evaluate_parameter_dict
    raise TypeError(
TypeError: Allowed value types are bytes, bool, int, float, str, Sequence[bool], Sequence[int], Sequence[float], Sequence[str]. Got <class 'NoneType'>.If the parameter is meant to be a string, try wrapping it in launch_ros.parameter_descriptions.ParameterValue(value, value_type=str)
igcs@igcs:~$ 

```

Hi, Im a little lost in ROS2, compiled buy I coudnt make it work, uninstaled deleted every folder or file , after installed from  ros repository .deb, but sends the above error. 
uninstaled , installed, same
20.04, foxy, cuda 11.4, gtsam4, etc.

**Comment by stevemartinov** [comment]
If you read the error then it is quite obvious what is the error...
It is not the error with the binaries, you just gave wrong value type in the launch file

**Comment by FPSychotic** [comment]
> If you read the error then it is quite obvious what is the error... It is not the error with the binaries, you just gave wrong value type in the launch file

I read the error and I don't understand it, I didn't change any valor in the launch file.
Can you be more explicit in any way, or give any solution?
Thanks

**Comment by matlabbe** [comment]
Please use ros2 branch, there is a commit [here](https://github.com/introlab/rtabmap_ros/commit/b81009b9f6f3491c5132ab5547ad73e9475ab345) that should fix that problem (https://github.com/introlab/rtabmap_ros/issues/725).
